### ISSUE TITLE
 Attempted import error: 'getNeighborsBase32' is not exported from 'geohashing' (imported as 'getNeighborsBase32').

### ISSUE THREAD

**Issue by Born-Winga** [arseny034/geohashing#1]
I am getting the error above importing _getNeighborsBase32_ from the lib  `Attempted import error: 'getNeighborsBase32' is not exported from 'geohashing' (imported as 'getNeighborsBase32').` Also from the linter it seems to not be exported.

<img width="694" alt="Screenshot 2024-04-04 at 11 11 30" src="https://github.com/arseny034/geohashing/assets/29257869/7bb0b257-7718-4fef-ba6e-265639bed6ca">

**Comment by arseny034** [comment]
Thanks for reporting! This was a bug, fixed in [1.1.4](https://github.com/arseny034/geohashing/releases/tag/v1.1.4)
